language: c
install:
  - curl -O http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - tar xfz rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - (cd rust-nightly-x86_64-unknown-linux-gnu/ && sudo ./install.sh)
script:
  - git clone git://github.com/BurntSushi/quickcheck
    && mkdir -p ./build/
    && rustc ./quickcheck/src/lib.rs --out-dir ./build/
    && make test

